spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/intkudago
    username: hello
    password: hello
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
